# use whole build server in single docker file such as build,test,publish,run...

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app
COPY . .
RUN dotnet publish ./src/Game.Services.Messaging.API -c Release -o ./bin/Docker 

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build ./src/Game.Services.Messaging.API/bin/Docker .
ENV ASPNETCORE_URLS http://*:7002
ENV ASPNETCORE_ENVIRONMENT docker
EXPOSE 7002
ENTRYPOINT dotnet Game.Services.Messaging.API.dll